// examples/nuxt/template-hierarchy-data-fetching/example-app/components/wp-templates/archive.vue
<script setup>
import { computed } from "vue";
import { useGraphQL, gql } from "../../lib/client";
import PostListing from "../templates/listing/Post.vue";
import Loading from "../Loading.vue";
import EmptyState from "../EmptyState.vue";
const props = defineProps({
  templateData: Object,
});
const archiveQuery = gql`
  query ArchiveTemplateNodeQuery($uri: String!) {
    archive: nodeByUri(uri: $uri) {
      __typename

      ... on User {
        contentNodes: posts {
          nodes {
            id
            uri
            title
            excerpt
            date
            featuredImage {
              node {
                sourceUrl
                altText
              }
            }
            ... on Post {
              categories {
                nodes {
                  name
                  slug
                }
              }
              tags {
                nodes {
                  name
                  slug
                }
              }
            }
          }
        }
      }

      ... on TermNode {
        name
        description
      }

      ... on Tag {
        name
        description
        contentNodes {
          nodes {
            id
            uri
            date
            ... on NodeWithTitle {
              title
            }
            ... on NodeWithExcerpt {
              excerpt
            }
            ... on NodeWithFeaturedImage {
              featuredImage {
                node {
                  sourceUrl
                  altText
                }
              }
            }
            ... on Post {
              categories {
                nodes {
                  name
                  slug
                }
              }
              tags {
                nodes {
                  name
                  slug
                }
              }
            }
          }
        }
      }

      ... on Category {
        name
        description
        contentNodes {
          nodes {
            id
            uri
            date
            ... on NodeWithTitle {
              title
            }
            ... on NodeWithExcerpt {
              excerpt
            }
            ... on NodeWithFeaturedImage {
              featuredImage {
                node {
                  sourceUrl
                  altText
                }
              }
            }
            ... on Post {
              categories {
                nodes {
                  name
                  slug
                }
              }
              tags {
                nodes {
                  name
                  slug
                }
              }
            }
          }
        }
      }
    }
  }
`;
const uri = useRoute().path || "/";
const { data, loading, error } = useGraphQL(
  archiveQuery,
  { uri: props.templateData?.uri || uri },
  {
    key: `archive-${props.templateData?.uri || uri}`,
    loadingText: "Loading archive...",
  }
);

const archive = computed(() => data.value?.archive || null);
</script>

<template>
  <main class="container">
    <!-- Loading state -->
    <div v-if="loading" class="text-center">
      <Loading />
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="text-center">
      <h1 class="">Error</h1>
      <p>{{ error.message }}</p>
    </div>

    <!-- Archive content -->
    <div v-else-if="archive">
      <header class="mb-4 text-center">
        <h1 class="">{{ archive.name }}</h1>
        <div
          v-if="archive.description"
          class=""
          v-html="archive.description"
        ></div>
      </header>

      <template v-if="archive.contentNodes.nodes">
        <PostListing
          :posts="archive.contentNodes.nodes"
          :loading="loading"
          :cols="3"
        />
      </template>

      <!-- Empty state -->
      <div v-else class="text-center">
        <EmptyState text="There are no posts available in here." />
      </div>
    </div>

    <!-- Fallback -->
    <div v-else class="py-10 text-center">
      <h1 class="text-2xl font-bold mb-2">Archive Not Found</h1>
      <p>The requested archive could not be found.</p>
      <NuxtLink to="/" class="text-blue-500 hover:underline mt-4 inline-block">
        Return home
      </NuxtLink>
    </div>
  </main>
</template>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/wp-templates/archive/archive.component.ts
import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { fetchGraphQL, gql } from '../../../utils/graphql.service';
import { Post } from '../../../interfaces/post.interface';
import { PostListingComponent } from '../../post-listing/post-listing.component';
import { LoadingComponent } from '../../loading/loading.component';
import { NotFoundComponent } from '../../not-found/not-found.component';
import { EmptyStateComponent } from '../../empty-state/empty-state.component';

interface ArchiveNode {
  __typename: string;
  name: string;
  description?: string;
  contentNodes?: {
    nodes: Post[];
  };
  posts?: {
    nodes: Post[];
  };
}

interface ArchiveResponse {
  archive: ArchiveNode;
}

@Component({
  selector: 'app-archive',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    LoadingComponent,
    EmptyStateComponent,
    NotFoundComponent,
    PostListingComponent,
  ],
  templateUrl: './archive.component.html',
  styleUrl: './archive.component.scss',
})
export class ArchiveComponent implements OnInit {
  data = signal<ArchiveResponse | null>(null);
  loading = signal(true);
  error = signal<any>(null);

  private archiveQuery = gql`
    query ArchiveTemplateNodeQuery($uri: String!) {
      archive: nodeByUri(uri: $uri) {
        __typename

        ... on User {
          contentNodes: posts {
            nodes {
              id
              uri
              title
              excerpt
              date
              featuredImage {
                node {
                  sourceUrl
                  altText
                }
              }
              ... on Post {
                categories {
                  nodes {
                    name
                    slug
                  }
                }
                tags {
                  nodes {
                    name
                    slug
                  }
                }
              }
            }
          }
        }

        ... on TermNode {
          name
          description
        }

        ... on Tag {
          name
          description
          contentNodes {
            nodes {
              id
              uri
              date
              ... on NodeWithTitle {
                title
              }
              ... on NodeWithExcerpt {
                excerpt
              }
              ... on NodeWithFeaturedImage {
                featuredImage {
                  node {
                    sourceUrl
                    altText
                  }
                }
              }
              ... on Post {
                categories {
                  nodes {
                    name
                    slug
                  }
                }
                tags {
                  nodes {
                    name
                    slug
                  }
                }
              }
            }
          }
        }

        ... on Category {
          name
          description
          contentNodes {
            nodes {
              id
              uri
              date
              ... on NodeWithTitle {
                title
              }
              ... on NodeWithExcerpt {
                excerpt
              }
              ... on NodeWithFeaturedImage {
                featuredImage {
                  node {
                    sourceUrl
                    altText
                  }
                }
              }
              ... on Post {
                categories {
                  nodes {
                    name
                    slug
                  }
                }
                tags {
                  nodes {
                    name
                    slug
                  }
                }
              }
            }
          }
        }
      }
    }
  `;

  // Computed properties using Angular signals
  archive = computed(() => {
    return this.data()?.archive || null;
  });

  posts = computed(() => {
    const archiveData = this.archive();
    if (!archiveData) return [];

    // Handle different archive types
    if (archiveData.contentNodes?.nodes) {
      return archiveData.contentNodes.nodes;
    }

    // Handle User archives (posts field)
    if (archiveData.posts?.nodes) {
      return archiveData.posts.nodes;
    }

    return [];
  });

  hasContent = computed(() => {
    return this.posts().length > 0;
  });

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.loadArchive();
  }

  private loadArchive(): void {
    const uri = this.router.url;

    this.loading.set(true);
    this.error.set(null);

    fetchGraphQL<ArchiveResponse>(this.archiveQuery, { uri })
      .then((response) => {
        this.data.set(response);
      })
      .catch((error) => {
        this.error.set(error);
      })
      .finally(() => {
        this.loading.set(false);
      });
  }
  /**
   * Get archive type for display
   */
  getArchiveType(): string {
    const archiveData = this.archive();
    if (!archiveData) return 'Archive';

    switch (archiveData.__typename) {
      case 'Category':
        return 'Category';
      case 'Tag':
        return 'Tag';
      case 'User':
        return 'Author';
      default:
        return 'Archive';
    }
  }

  /**
   * Check if archive has description
   */
  hasDescription(): boolean {
    const archiveData = this.archive();
    return !!archiveData?.description?.trim();
  }
}

<main class="container">
  <!-- Loading state -->
  <div *ngIf="loading()" class="text-center">
    <app-loading text="Loading archive..."></app-loading>
  </div>

  <!-- Error state -->
  <div *ngIf="error() && !loading()" class="text-center error-container">
    <h1 class="error-title">Error</h1>
    <p class="error-message">
      {{ error()?.message || "Failed to load archive" }}
    </p>
    <button (click)="retry()" class="btn btn-primary">Try Again</button>
  </div>

  <!-- Archive content -->
  <div *ngIf="archive() && !loading() && !error()">
    <header class="archive-header">
      <h1 class="archive-title">
        {{ getArchiveType() }}: {{ archive()!.name }}
      </h1>
      <div
        *ngIf="hasDescription()"
        class="archive-description"
        [innerHTML]="archive()!.description"
      ></div>
      <div class="archive-meta">
        <span class="posts-count">{{
          posts().length === 0
            ? "No posts found"
            : posts().length +
              " " +
              (posts().length === 1 ? "post" : "posts") +
              " found"
        }}</span>
      </div>
    </header>

    <!-- Posts listing -->
    <div *ngIf="hasContent()">
      <app-post-listing [posts]="posts()" [loading]="false" [cols]="3">
      </app-post-listing>
    </div>

    <!-- Empty state -->
    <div *ngIf="!hasContent()" class="text-center">
      <app-empty-state
        text="There are no posts available in here."
      ></app-empty-state>
    </div>
  </div>

  <!-- Fallback when no archive data -->
  <div *ngIf="!archive() && !loading() && !error()" class="fallback-container">
    <h1 class="fallback-title">Archive Not Found</h1>
    <p class="fallback-message">The requested archive could not be found.</p>
    <a routerLink="/" class="btn btn-primary"> Return Home </a>
  </div>
</main>
