// examples/next/woocommerce/example-app/src/components/Footer/Footer.tsx
import { useQuery, gql } from "@apollo/client";
import { FooterData } from "@/interfaces/navigation.interface";

export default function Footer({ footerData }: { footerData: FooterData | null }) {
	const settingsData = footerData?.settings;
	return (
		<footer className="footer">
			<div className="footer-content">
				<p>
					&copy; {new Date().getFullYear()} {settingsData?.generalSettings?.title || "My Site"}. All rights reserved.
				</p>
			</div>

			<style jsx>{`
				.footer {
					background: #f8f9fa;
					border-top: 1px solid #e1e5e9;
					padding: 1rem 0;
					margin-top: auto;
				}

				.footer-content {
					max-width: 1200px;
					margin: 0 auto;
					padding: 0 1rem;
					display: flex;
					justify-content: center;
					align-items: center;
				}

				.footer-content p {
					margin: 0;
					color: #6c757d;
					font-size: 14px;
				}

				@media (max-width: 768px) {
					.footer-content p {
						font-size: 12px;
						text-align: center;
					}
				}
			`}</style>
		</footer>
	);
}

// examples/nuxt/data-fetch/example-app/components/Footer.vue
<script setup>
import { computed } from 'vue';
import { useGraphQL, gql } from '../lib/client';

// Query to fetch footer data
const FOOTER_QUERY = gql`
  query GetFooterData {
    generalSettings {
      title
    }        
  }
`;

const { data } = useGraphQL(FOOTER_QUERY);

const siteTitle = computed(() => data.value?.generalSettings?.title || 'My WordPress Site');
const currentYear = new Date().getFullYear();
</script>

<template>
  <footer class="footer">
      <div class="footer-content">
        <p>© {{ currentYear }} <NuxtLink to="/">{{ siteTitle }}</NuxtLink>. All rights reserved.</p>
        <p>Built with WordPress, Nuxt, and WPGraphQL.</p>
      </div>  
  </footer>
</template>

<style scoped>
.footer {
  border-top: 1px solid #e5e7eb;
  color: #333;
  margin: 2rem 0 0 0;
  padding-top: 2rem;
  padding-bottom: 1.5rem; 
}
.footer-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 1rem; 
  text-align: center; 
}
</style>
