// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/header/header.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { fetchGraphQLSSR, gql } from '../../utils/graphql.service';
import { flatListToHierarchical } from '../../utils/utils';
interface MenuItem {
  id: string;
  label: string;
  uri: string;
  parentId?: string;
  target?: string;
  cssClasses?: string[];
  title?: string;
  description?: string;
  children?: MenuItem[];
}

interface SiteSettings {
  generalSettings: {
    title: string;
  };
}

interface NavigationResponse {
  menu: {
    menuItems: {
      pageInfo: {
        hasNextPage: boolean;
        endCursor: string;
      };
      nodes: MenuItem[];
    };
  };
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent implements OnInit {
  // Reactive signals for component state
  siteInfo = signal<{ title: string }>({ title: 'HeadlessWP Toolkit' });
  menuItems = signal<MenuItem[]>([]);
  settingsLoading = signal<boolean>(false);
  navigationLoading = signal<boolean>(false);
  error = signal<string | null>(null);

  constructor(private router: Router) {}

  ngOnInit() {
    this.loadSiteSettings();
    this.loadNavigation();
  }

  private loadSiteSettings() {
    const SETTINGS_QUERY = gql`
      query HeaderSettingsQuery {
        generalSettings {
          title
        }
      }
    `;

    this.settingsLoading.set(true);

    fetchGraphQLSSR<SiteSettings>(SETTINGS_QUERY, {})
      .then((data) => {
        if (data?.generalSettings?.title) {
          this.siteInfo.set({ title: data.generalSettings.title });
        }
        this.settingsLoading.set(false);
      })
      .catch((error) => {
        console.error('Error loading site settings:', error);
        this.error.set('Failed to load site settings');
        this.settingsLoading.set(false);
      });
  }

  private loadNavigation() {
    const NAVIGATION_QUERY = gql`
      query HeaderNavigationQuery($after: String = null) {
        menu(id: "primary", idType: LOCATION) {
          menuItems(first: 100, after: $after) {
            pageInfo {
              hasNextPage
              endCursor
            }
            nodes {
              id
              label
              uri
              parentId
              target
              cssClasses
              title
              description
            }
          }
        }
      }
    `;

    this.navigationLoading.set(true);

    fetchGraphQLSSR<NavigationResponse>(NAVIGATION_QUERY, {})
      .then((data) => {
        if (data?.menu?.menuItems?.nodes) {
          const hierarchicalMenu = this.flatListToHierarchical(
            data.menu.menuItems.nodes
          );
          this.menuItems.set(hierarchicalMenu);
        }
        this.navigationLoading.set(false);
      })
      .catch((error) => {
        console.error('Error loading navigation:', error);
        this.navigationLoading.set(false);
      });
  }
  private flatListToHierarchical(items: MenuItem[]): MenuItem[] {
    return flatListToHierarchical(items, {
      idKey: 'id',
      parentKey: 'parentId',
      childrenKey: 'children',
    });
  }
  isActive(item: MenuItem): boolean {
    if (!item.uri) return false;

    // Format the URI for comparison
    let cleanUri = item.uri.startsWith('/') ? item.uri.substring(1) : item.uri;
    cleanUri = cleanUri.endsWith('/') ? cleanUri.slice(0, -1) : cleanUri;

    // Compare with current route path
    const currentPath = this.router.url;
    const cleanCurrentPath = currentPath.startsWith('/')
      ? currentPath.substring(1)
      : currentPath;

    return `/${cleanUri}` === currentPath || cleanUri === cleanCurrentPath;
  }

  onMenuItemClick(item: MenuItem) {
    if (item.uri) {
      if (item.target === '_blank' || item.uri.startsWith('http')) {
        window.open(item.uri, item.target || '_self');
      } else {
        this.router.navigate([item.uri]);
      }
    }
  }
  dropdownClass(level: number): string {
    return level === 0 ? 'dropdown-top' : 'dropdown-submenu';
  }
}

<header class="header">
  <div class="main-header-wrapper">
    <div class="site-title-wrapper">
      <a routerLink="/" class="site-title">
        <h1 *ngIf="siteInfo()?.title && !settingsLoading()">
          {{ siteInfo().title }}
        </h1>
      </a>
    </div>
    <nav class="nav">
      <div *ngIf="navigationLoading()" class="nav-loading">
        <span>Loading navigation...</span>
      </div>
      <ng-container *ngFor="let item of menuItems()">
        <ng-container
          *ngTemplateOutlet="
            menuItemTemplate;
            context: { $implicit: item, level: 0 }
          "
        >
        </ng-container>
      </ng-container>

      <!-- Recursive menu item template -->
      <ng-template #menuItemTemplate let-item let-level="level">
        <div
          class="group relative dropdown-item-container"
          [class]="'nav-item-level-' + level"
          [class.has-children]="item.children && item.children.length > 0"
        >
          <a
            [href]="item.uri"
            [target]="item.target || '_self'"
            [class]="
              'nav-link nav-link-level-' +
              level +
              ' ' +
              (item.cssClasses?.join(' ') || '')
            "
            [class.active]="isActive(item)"
            [title]="item.description || item.title"
            (click)="onMenuItemClick(item); $event.preventDefault()"
          >
            {{ item.label }}
            <span
              *ngIf="item.children && item.children.length > 0"
              class="dropdown-indicator"
              [class]="'dropdown-indicator-level-' + level"
            >
              ▼
            </span>
          </a>

          <!-- Recursive dropdown menu for children -->
          <div *ngIf="item.children && item.children.length > 0"
              class="dropdown"
              [class]="dropdownClass(level)">
            <ul
              *ngIf="item.children && item.children.length > 0"
              class="dropdown-item-container"
            >
              <ng-container *ngFor="let child of item.children">
                <ng-container
                  *ngTemplateOutlet="
                    menuItemTemplate;
                    context: { $implicit: child, level: level + 1 }
                  "
                >
                </ng-container>
              </ng-container>
            </ul>
          </div>
        </div>
      </ng-template>
    </nav>
  </div>
</header>

<div *ngIf="settingsLoading()" class="header-loading">
  <div class="loading-spinner"></div>
  <span>Loading header...</span>
</div>

<div *ngIf="error()" class="header-error">
  <p>{{ error() }}</p>
</div>

// examples/nuxt/data-fetch/example-app/components/Header.vue
<script setup>
import { computed } from 'vue';
import { useGraphQL, gql } from '../lib/client';
import { useRoute } from 'vue-router';
import NavigationItem from './templates/header/NavigationItem.vue';
import { flatListToHierarchical } from '../lib/utils';

// Get current route for active menu item
const route = useRoute();

const SETTINGS_QUERY = gql`
  query HeaderSettingsQuery {
    generalSettings {
      title
    }
  }
`;

const NAVIGATION_QUERY = gql`
  query HeaderNavigationQuery($after: String = null) {
    menu(id: "primary", idType: LOCATION) {
      menuItems(first: 100, after: $after) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          label
          uri
          parentId
          target
          cssClasses
          title
          description
        }
      }
    }
  }
`;

// Use unique keys for proper SSR state management
const {
  data: settingsData,
  loading: settingsLoading,
  error: settingsError
} = useGraphQL(SETTINGS_QUERY, {}, {
  key: 'header-settings',
  loadingText: 'Loading site title...'
});

const {
  data: navigationData,
} = useGraphQL(NAVIGATION_QUERY, {}, {
  key: 'header-navigation',
  loadingText: 'Loading navigation...'
});


const siteInfo = computed(() => {
  const title = settingsData.value?.generalSettings?.title;

  return {
    title: title
  };
});

// Get flat menu items
const flatMenuItems = computed(() => {
  return navigationData.value?.menu?.menuItems?.nodes || [];
});

// Convert flat menu to hierarchical structure
const menuItems = computed(() => {
  return flatListToHierarchical(flatMenuItems.value);
});

// Determine if a menu item is active
const isActive = (item) => {
  if (!item.uri) return false;

  // Format the URI for comparison
  let cleanUri = item.uri.startsWith('/') ? item.uri.substring(1) : item.uri;
  cleanUri = cleanUri.endsWith('/') ? cleanUri.slice(0, -1) : cleanUri;

  // Compare with current route path
  return `/${cleanUri}` === route.path;
};
</script>

<template>
  <header class="header" v-if="!settingsLoading">
    <div class="main-header-wrapper">
      <div class="site-title-wrapper">
        <NuxtLink to="/">
          <template v-if="siteInfo.title">
            {{ siteInfo.title }}
          </template>
        </NuxtLink>
      </div>

      <nav class="nav">
        <!-- Navigation items -->
        <template v-if="menuItems.length > 0">
          <NavigationItem v-for="item in menuItems" :key="item.id" :item="item" :is-active="isActive(item)" />
        </template>
      </nav>
    </div>
  </header>
</template>

<style scoped lang="scss">
@use '@/assets/scss/components/header/header';
</style>
