// examples/angular/example-app/src/app/components/header/header.component.ts
import { Component, Input, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { GraphQLService, gql } from '../../shared/utils/graphql.service';

interface MenuItem {
  id: string;
  label: string;
  uri: string;
  parentId?: string;
  target?: string;
  cssClasses?: string[];
  title?: string;
  description?: string;
  children?: MenuItem[];
}

interface SiteSettings {
  generalSettings: {
    title: string;
  };
}

interface NavigationResponse {
  menu: {
    menuItems: {
      pageInfo: {
        hasNextPage: boolean;
        endCursor: string;
      };
      nodes: MenuItem[];
    };
  };
}

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent implements OnInit {
  // Reactive signals for component state
  siteInfo = signal<{ title: string }>({ title: 'HeadlessWP Toolkit' });
  menuItems = signal<MenuItem[]>([]);
  settingsLoading = signal<boolean>(false);
  navigationLoading = signal<boolean>(false);
  error = signal<string | null>(null);

  constructor(
    private graphqlService: GraphQLService,
    private router: Router
  ) {}

  ngOnInit() {
    // Load data with a delay to avoid change detection issues
    setTimeout(() => {
      this.loadSiteSettings();
      this.loadNavigation();
    }, 0);
  }

  private loadSiteSettings() {
    if (!this.graphqlService) {
      console.error('GraphQLService is not available');
      return;
    }

    const SETTINGS_QUERY = gql`
      query HeaderSettingsQuery {
        generalSettings {
          title
        }
      }
    `;

    this.settingsLoading.set(true);
    
    this.graphqlService.query<SiteSettings>(SETTINGS_QUERY, {}).subscribe({
      next: (data: SiteSettings) => {
        if (data?.generalSettings?.title) {
          this.siteInfo.set({ title: data.generalSettings.title });
        }
        this.settingsLoading.set(false);
      },
      error: (error: any) => {
        console.error('Error loading site settings:', error);
        this.error.set('Failed to load site settings');
        this.settingsLoading.set(false);
      }
    });
  }

  private loadNavigation() {
    if (!this.graphqlService) {
      console.error('GraphQLService is not available');
      return;
    }

    const NAVIGATION_QUERY = gql`
      query HeaderNavigationQuery($after: String = null) {
        menu(id: "primary", idType: LOCATION) {
          menuItems(first: 100, after: $after) {
            pageInfo {
              hasNextPage
              endCursor
            }
            nodes {
              id
              label
              uri
              parentId
              target
              cssClasses
              title
              description
            }
          }
        }
      }
    `;

    this.navigationLoading.set(true);
    
    this.graphqlService.query<NavigationResponse>(NAVIGATION_QUERY, {}).subscribe({
      next: (data: NavigationResponse) => {
        if (data?.menu?.menuItems?.nodes) {
          const hierarchicalMenu = this.flatListToHierarchical(data.menu.menuItems.nodes);
          this.menuItems.set(hierarchicalMenu);
        }
        this.navigationLoading.set(false);
      },
      error: (error: any) => {
        console.error('Error loading navigation:', error);       
        this.navigationLoading.set(false);
      }
    });
  }

  private flatListToHierarchical(items: MenuItem[]): MenuItem[] {
    const map = new Map<string, MenuItem>();
    const roots: MenuItem[] = [];

    // First pass: create map of all items
    items.forEach(item => {
      map.set(item.id, { ...item, children: [] });
    });

    // Second pass: build hierarchy
    items.forEach(item => {
      const mappedItem = map.get(item.id)!;
      
      if (item.parentId && map.has(item.parentId)) {
        const parent = map.get(item.parentId)!;
        if (!parent.children) {
          parent.children = [];
        }
        parent.children.push(mappedItem);
      } else {
        roots.push(mappedItem);
      }
    });

    return roots;
  }

  isActive(item: MenuItem): boolean {
    if (!item.uri) return false;
    
    // Format the URI for comparison
    let cleanUri = item.uri.startsWith('/') ? item.uri.substring(1) : item.uri;
    cleanUri = cleanUri.endsWith('/') ? cleanUri.slice(0, -1) : cleanUri;
    
    // Compare with current route path
    const currentPath = this.router.url;
    const cleanCurrentPath = currentPath.startsWith('/') ? currentPath.substring(1) : currentPath;
    
    return `/${cleanUri}` === currentPath || cleanUri === cleanCurrentPath;
  }

  onMenuItemClick(item: MenuItem) {
    if (item.uri) {
      // Handle external links
      if (item.target === '_blank' || item.uri.startsWith('http')) {
        window.open(item.uri, item.target || '_self');
      } else {
        // Navigate internally
        this.router.navigate([item.uri]);
      }
    }
  }
}
<header class="header">
  <div class="main-header-wrapper">
    <div class="site-title-wrapper">
      <a routerLink="/" class="site-title">
        <h1 *ngIf="siteInfo()?.title && !settingsLoading()">
          {{ siteInfo().title }}
        </h1>
      </a>
    </div>
    <nav class="nav">
      <div *ngIf="navigationLoading()" class="nav-loading">
        <span>Loading navigation...</span>
      </div>

      <!-- Navigation items -->
      <!-- <ul
        *ngIf="!navigationLoading() && menuItems().length > 0;"
        class="nav-menu"
      > -->
        <ng-container *ngFor="let item of menuItems()">
          <ng-container 
            *ngTemplateOutlet="menuItemTemplate; context: { $implicit: item, level: 0 }">
          </ng-container>
        </ng-container>
      <!-- </ul> -->
      
      <!-- Recursive menu item template -->
      <ng-template #menuItemTemplate let-item let-level="level">
        <li
          class="nav-item group relative"
          [class]="'nav-item-level-' + level"
          [class.has-children]="item.children && item.children.length > 0"
        >
          <a
            [href]="item.uri"
            [target]="item.target || '_self'"
            [class]="'nav-link nav-link-level-' + level + ' ' + (item.cssClasses?.join(' ') || '')"
            [class.active]="isActive(item)"
            [title]="item.description || item.title"
            (click)="onMenuItemClick(item); $event.preventDefault()"
          >
            {{ item.label }}
            <!-- Add dropdown indicator for items with children -->
            <span 
              *ngIf="item.children && item.children.length > 0" 
              class="dropdown-indicator"
              [class]="'dropdown-indicator-level-' + level">
              ▼
            </span>
          </a>

          <!-- Recursive dropdown menu for children -->
          <ul
            *ngIf="item.children && item.children.length > 0"
            class="dropdown-menu"
            [class]="'dropdown-menu-level-' + level"
          >
            <ng-container *ngFor="let child of item.children">
              <ng-container 
                *ngTemplateOutlet="menuItemTemplate; context: { $implicit: child, level: level + 1 }">
              </ng-container>
            </ng-container>
          </ul>
        </li>
      </ng-template>
    </nav>
  </div>
</header>

<div *ngIf="settingsLoading()" class="header-loading">
  <div class="loading-spinner"></div>
  <span>Loading header...</span>
</div>

<div *ngIf="error()" class="header-error">
  <p>{{ error() }}</p>
</div>

// examples/nuxt/data-fetch/example-app/components/Header.vue
<script setup>
import { computed } from 'vue';
import { useGraphQL, gql } from '../lib/client';
import { useRoute } from 'vue-router';
import NavigationItem from './templates/header/NavigationItem.vue';
import { flatListToHierarchical } from '../lib/utils';

// Get current route for active menu item
const route = useRoute();

const SETTINGS_QUERY = gql`
  query HeaderSettingsQuery {
    generalSettings {
      title
    }
  }
`;

const NAVIGATION_QUERY = gql`
  query HeaderNavigationQuery($after: String = null) {
    menu(id: "primary", idType: LOCATION) {
      menuItems(first: 100, after: $after) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          label
          uri
          parentId
          target
          cssClasses
          title
          description
        }
      }
    }
  }
`;

// Use unique keys for proper SSR state management
const {
  data: settingsData,
  loading: settingsLoading,
  error: settingsError
} = useGraphQL(SETTINGS_QUERY, {}, {
  key: 'header-settings',
  loadingText: 'Loading site title...'
});

const {
  data: navigationData,
} = useGraphQL(NAVIGATION_QUERY, {}, {
  key: 'header-navigation',
  loadingText: 'Loading navigation...'
});


const siteInfo = computed(() => {
  const title = settingsData.value?.generalSettings?.title;

  return {
    title: title
  };
});

// Get flat menu items
const flatMenuItems = computed(() => {
  return navigationData.value?.menu?.menuItems?.nodes || [];
});

// Convert flat menu to hierarchical structure
const menuItems = computed(() => {
  return flatListToHierarchical(flatMenuItems.value);
});

// Determine if a menu item is active
const isActive = (item) => {
  if (!item.uri) return false;

  // Format the URI for comparison
  let cleanUri = item.uri.startsWith('/') ? item.uri.substring(1) : item.uri;
  cleanUri = cleanUri.endsWith('/') ? cleanUri.slice(0, -1) : cleanUri;

  // Compare with current route path
  return `/${cleanUri}` === route.path;
};
</script>

<template>
  <header class="header" v-if="!settingsLoading">
    <div class="main-header-wrapper">
      <div class="site-title-wrapper">
        <NuxtLink to="/">
          <template v-if="siteInfo.title">
            {{ siteInfo.title }}
          </template>
        </NuxtLink>
      </div>

      <nav class="nav">
        <!-- Navigation items -->
        <template v-if="menuItems.length > 0">
          <NavigationItem v-for="item in menuItems" :key="item.id" :item="item" :is-active="isActive(item)" />
        </template>
      </nav>
    </div>
  </header>
</template>

<style scoped lang="scss">
@use '@/assets/scss/components/header/header';
</style>
