// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/loading/loading.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loading',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './loading.component.html',
  styleUrl: './loading.component.scss'
})
export class LoadingComponent {
  @Input() text: string = ''; // Default to empty string, so text only shows if provided
  @Input() showSpinner: boolean = true; // Show spinner by default
}
<div class="loading-container">
  <div *ngIf="showSpinner" class="spinner"></div>
  <p *ngIf="text" class="loading-text">{{ text }}</p>
</div>

// examples/nuxt/data-fetch/example-app/components/Loading.vue

<script setup>
import { defineProps } from 'vue';

const props = defineProps({
  text: {
    type: String,
    default: '', // Default to empty string, so text only shows if provided
  },
  showSpinner: {
    type: Boolean,
    default: true, // Show spinner by default
  },
});
</script>

<template>
  <div class="loading-container">
    <div v-if="showSpinner" class="spinner"></div>
    <p v-if="text" class="loading-text">{{ text }}</p>
  </div>
</template>

<style scoped lang="scss">
@use '@/assets/scss/components/loading';
</style>
