// examples/nuxt/data-fetch/example-app/components/wp-templates/singular.vue
<script setup>
import { computed } from "vue";
import { useGraphQL, gql } from "../../lib/client";
import { formatDate } from "../../lib/utils";
import Comments from "../Comments.vue";
import Loading from "../Loading.vue";
import NotFound from "../components/404.vue";

const POST_QUERY = gql`
  query GetPost($slug: ID!) {
    post(id: $slug, idType: SLUG) {
      id
      databaseId
      title
      date
      content
      commentCount
      categories {
        nodes {
          name
          uri
        }
      }
      tags {
        nodes {
          name
          uri
        }
      }
      author {
        node {
          name
          avatar {
            url
          }
        }
      }
      featuredImage {
        node {
          sourceUrl
          altText
        }
      }
    }
  }
`;
const uri = useRoute().path || "/";
const { data, loading, error } = useGraphQL(POST_QUERY, { slug: uri });

const post = computed(() => data.value?.post || null);
const postId = computed(() => post.value?.databaseId || null);
</script>

<template>
  <div class="container">
    <!-- Loading state -->
    <template v-if="loading">
      <Loading />
    </template>

    <!-- Error state -->
    <div v-else-if="error" class="py-10 text-center">
      <h1 class="text-2xl font-bold text-red-500 mb-2">Error</h1>
      <p>{{ error.message }}</p>
      <NuxtLink to="/" class="text-blue-500 hover:underline mt-4 inline-block">
        Return to homepage
      </NuxtLink>
    </div>

    <!-- Post content -->
    <article v-else-if="post" class="py-10">
      <h1 class="text-center">{{ post.title }}</h1>
      <!-- Featured image -->
      <img
        v-if="post.featuredImage?.node"
        :src="post.featuredImage.node.sourceUrl"
        :alt="post.featuredImage.node.altText || post.title"
        class=""
      />

      <!-- Post content -->
      <div class="prose prose-lg max-w-none mb-8" v-html="post.content"></div>
      <!-- Post header -->

      <!-- Post meta -->
      <div class="post-meta">
        <div class="flex items-center text-gray-500 mb-6">
          <div v-if="post.author?.node" class="flex items-center mr-6">
            <img
              v-if="post.author.node.avatar?.url"
              :src="post.author.node.avatar.url"
              :alt="post.author.node.name"
              class="w-8 h-8 rounded-full mr-2"
            />
            <span>By {{ post.author.node.name }}</span>
          </div>
          <time>{{ formatDate(post.date) }}</time>
        </div>

        <!-- Categories -->
        <div v-if="post.categories?.nodes?.length" class="flex">
          Categories:
          <NuxtLink
            v-for="category in post.categories.nodes"
            :key="category.name"
            :to="category.uri"
            class=""
          >
            {{ category.name }}
          </NuxtLink>
        </div>
        <!-- Tags -->
        <div v-if="post.tags?.nodes?.length" class="">
          <h3 class="">Tags:</h3>
          <div class="flex">
            <NuxtLink
              v-for="tag in post.tags.nodes"
              :key="tag.name"
              :to="tag.uri"
              class=""
            >
              {{ tag.name }}
            </NuxtLink>
          </div>
        </div>
      </div>
      <Comments v-if="postId" :post-id="postId" />
    </article>

    <template v-else>
      <NotFound />
    </template>
  </div>
</template>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/wp-templates/singular/singular.component.ts
import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { gql, fetchGraphQLSSR } from '../../../utils/graphql.service';
import {
  Post,
  Author,
  Category,
  Tag,
  FeaturedImage,
} from '../../../interfaces/post.interface';
import { LoadingComponent } from '../../loading/loading.component';
import { CommentsComponent } from '../../comments/comments.component';
import { NotFoundComponent } from '../../not-found/not-found.component';
import { EmptyStateComponent } from '../../empty-state/empty-state.component';
import { formatDate } from '../../../utils/utils';

interface PostResponse {
  post: Post;
}

@Component({
  selector: 'app-singular',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    LoadingComponent,
    NotFoundComponent,
    CommentsComponent,
    EmptyStateComponent,
  ],
  templateUrl: './singular.component.html',
  styleUrl: './singular.component.scss',
})
export class SingularComponent implements OnInit {
  data = signal<PostResponse | null>(null);
  loading = signal(true);
  error = signal<any>(null);

  private POST_QUERY = gql`
    query GetPost($slug: ID!) {
      post(id: $slug, idType: SLUG) {
        id
        databaseId
        title
        date
        content
        commentCount
        categories {
          nodes {
            name
            uri
          }
        }
        tags {
          nodes {
            name
            uri
          }
        }
        author {
          node {
            name
            avatar {
              url
            }
          }
        }
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
      }
    }
  `;

  post = computed(() => {
    return this.data()?.post || null;
  });

  postId = computed(() => {
    return this.post()?.databaseId || null;
  });

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.loadPost();
  }

  private loadPost(): void {
    const slug = this.router.url.split('/').pop() || '';

    console.log('🔍 Loading post for slug:', slug);

    this.loading.set(true);
    this.error.set(null);

    fetchGraphQLSSR<PostResponse>(this.POST_QUERY, { slug })
      .then((response) => {
        this.data.set(response);
      })
      .catch((error) => {
        this.error.set(error);
      })
      .finally(() => {
        this.loading.set(false);
      });
  }

  formatDate(dateString: string): string {
    return formatDate(dateString);
  }

  hasCategories(): boolean {
    const currentPost = this.post();
    return !!(
      currentPost?.categories?.nodes && currentPost.categories.nodes.length > 0
    );
  }

  hasTags(): boolean {
    const currentPost = this.post();
    return !!(currentPost?.tags?.nodes && currentPost.tags.nodes.length > 0);
  }

  hasFeaturedImage(): boolean {
    const currentPost = this.post();
    return !!currentPost?.featuredImage?.node?.sourceUrl;
  }

  hasAuthor(): boolean {
    const currentPost = this.post();
    return !!currentPost?.author?.node;
  }

  hasAuthorAvatar(): boolean {
    const currentPost = this.post();
    return !!currentPost?.author?.node?.avatar?.url;
  }

  getCategoryLink(category: Category): string {
    return category.slug || `/category/${category.name.toLowerCase()}`;
  }

  getTagLink(tag: Tag): string {
    return tag.slug || `/tag/${tag.name.toLowerCase()}`;
  }

  isLastItem(index: number, array: any[]): boolean {
    return index === array.length - 1;
  }
}

<div class="container">
  <div *ngIf="loading()" class="text-center py-10">
    <app-loading text="Loading post..."></app-loading>
  </div>

  <div *ngIf="error() && !loading()" class="py-10 text-center error-container">
    <app-not-found
      [title]="'Error loading post'"
      [text]="error()?.message || 'An unexpected error occurred.'"
    ></app-not-found>
  </div>

  <article *ngIf="post() && !loading() && !error()" class="post-article">
    <header class="post-header">
      <h1 class="post-title">{{ post()!.title }}</h1>

      <div class="post-meta-header">
        <div *ngIf="hasAuthor()" class="author-info">
          <img
            *ngIf="hasAuthorAvatar()"
            [src]="post()!.author!.node.avatar!.url"
            [alt]="post()!.author!.node.name"
            class="author-avatar"
            loading="lazy"
          />
          <span class="author-name">By {{ post()!.author!.node.name }}</span>
        </div>
        <time class="post-date">{{ formatDate(post()!.date) }}</time>
      </div>
    </header>

    <div *ngIf="hasFeaturedImage()" class="featured-image-container">
      <img
        [src]="post()!.featuredImage!.node.sourceUrl"
        [alt]="post()!.featuredImage!.node.altText || post()!.title"
        class="featured-image"
        loading="lazy"
      />
    </div>

    <div
      class="post-content prose prose-lg max-w-none"
      [innerHTML]="post()!.content"
    ></div>

    <footer class="post-footer">
      <div *ngIf="hasCategories()" class="post-categories">
        <span class="meta-label">Categories:</span>
        <div class="categories-list">
          <a
            *ngFor="let category of post()!.categories!.nodes; let i = index"
            [routerLink]="getCategoryLink(category)"
            class="category-link"
          >
            {{ category.name
            }}{{ !isLastItem(i, post()!.categories!.nodes) ? ',' : '' }}
          </a>
        </div>
      </div>

      <div *ngIf="hasTags()" class="post-tags">
        <h3 class="meta-label">Tags:</h3>
        <div class="tags-list">
          <a
            *ngFor="let tag of post()!.tags!.nodes; let i = index"
            [routerLink]="getTagLink(tag)"
            class="tag-link"
          >
            {{ tag.name }}{{ !isLastItem(i, post()!.tags!.nodes) ? ',' : '' }}
          </a>
        </div>
      </div>
    </footer>

    <app-comments [postId]="postId()!"></app-comments>
  </article>

  <div *ngIf="!post() && !loading() && !error()">
    <app-empty-state></app-empty-state>
  </div>
</div>
