// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/blog/blog.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GraphQLService, GraphQLStateService, gql } from '../../utils/graphql.service';

interface Post {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  slug: string;
  uri: string;
  featuredImage?: {
    node: {
      sourceUrl: string;
      altText: string;
    };
  };
  categories?: {
    nodes: Array<{
      name: string;
      slug: string;
    }>;
  };
  tags?: {
    nodes: Array<{
      name: string;
      slug: string;
    }>;
  };
  author?: {
    node: {
      name: string;
      avatar: {
        url: string;
      };
    };
  };
}

interface PostsResponse {
  posts: {
    pageInfo: {
      hasNextPage: boolean;
      endCursor: string;
    };
    edges: Array<{
      cursor: string;
      node: Post;
    }>;
  };
}

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './blog.component.html',
  styleUrl: './blog.component.css'
})
export class BlogComponent implements OnInit {
  // Reactive signals
  postsData = signal<PostsResponse | null>(null);
  loading = signal<boolean>(false);
  error = signal<string | null>(null);

  // Computed signal to extract posts from the response
  posts = signal<Post[]>([]);

  private postsQuery: any;

  constructor(
    private graphqlService: GraphQLService,
    private graphqlState: GraphQLStateService
  ) {}

  ngOnInit() {
    // Create and execute the query
    this.postsQuery = this.graphqlState.createQuery<PostsResponse>(
      gql`
  query GetPosts(
    $first: Int = 9
    $after: String
    $category: String
    $tag: String
  ) {
    posts(
      first: $first
      after: $after
      where: { categoryName: $category, tag: $tag }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          tags {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`, {first: 10});

    // Subscribe to reactive state
    this.postsData = this.postsQuery.data;
    this.loading = this.postsQuery.loading;
    this.error = this.postsQuery.error;

    // Extract posts from the GraphQL response structure
    this.setupPostsExtraction();
  }

  private setupPostsExtraction() {
    // Use effect to update posts when data changes
    // For now, we'll do this manually in a simple way
    // You could use Angular's effect() here for more reactive approach
    const updatePosts = () => {
      const data = this.postsData();
      if (data?.posts?.edges) {
        const extractedPosts = data.posts.edges.map(edge => edge.node);
        this.posts.set(extractedPosts);
      } else {
        this.posts.set([]);
      }
    };

    // Update posts when data changes
    // For now, we'll call this periodically or on data updates
    updatePosts();
  }

  loadMorePosts() {
    // Example of refetching with new variables
    this.postsQuery.setVariables({ first: 20 }).subscribe({
      next: (result: any) => console.log('Loaded more posts:', result),
      error: (err: any) => console.error('Error loading more posts:', err)
    });
  }

  refreshPosts() {
    // Example of refetching with same variables
    this.postsQuery.refetch().subscribe({
      next: (result: any) => console.log('Refreshed posts:', result),
      error: (err: any) => console.error('Error refreshing posts:', err)
    });
  }
}

<div class="blog-container">
  <div class="blog-header">
    <h2>Latest Blog Posts</h2>
    <div class="blog-actions">
      <button
        class="btn btn-secondary"
        (click)="refreshPosts()"
        [disabled]="loading()"
      >
        Refresh
      </button>
      <button
        class="btn btn-primary"
        (click)="loadMorePosts()"
        [disabled]="loading()"
      >
        Load More
      </button>
    </div>
  </div>

  <!-- Loading State -->
  <div *ngIf="loading()" class="loading">
    <div class="loading-spinner"></div>
    <p>Loading posts...</p>
  </div>

  <!-- Error State -->
  <div *ngIf="error()" class="error">
    <p>Error loading posts: {{ error() }}</p>
    <button class="btn btn-primary" (click)="refreshPosts()">Try Again</button>
  </div>

  <!-- Posts List -->
  <div *ngIf="!loading() && !error() && posts().length > 0" class="posts-grid">
    <article
      *ngFor="let post of posts()"
      class="post-card"
      [attr.data-post-id]="post.id"
    >
      <div class="post-content">
        <h3 class="post-title">{{ post.title }}</h3>

        <div class="post-meta">
          <span class="post-date">{{ post.date | date: "mediumDate" }}</span>
          <span *ngIf="post.author" class="post-author"
            >by {{ post.author.node.name }}</span
          >
        </div>

        <!-- Featured Image -->
        <div *ngIf="post.featuredImage" class="post-image">
          <img
            [src]="post.featuredImage.node.sourceUrl"
            [alt]="post.featuredImage.node.altText || post.title"
            loading="lazy"
          />
        </div>

        <div class="post-excerpt" [innerHTML]="post.excerpt"></div>

        <!-- Categories and Tags -->
        <div
          class="post-taxonomy"
          *ngIf="post.categories?.nodes || post.tags?.nodes"
        >
          <div
            *ngIf="
              post.categories?.nodes &&
              (post.categories?.nodes?.length ?? 0) > 0
            "
            class="post-categories"
          >
            <span class="taxonomy-label">Categories:</span>
            <span
              *ngFor="let category of post.categories?.nodes; let last = last"
              class="taxonomy-item"
            >
              {{ category.name }}<span *ngIf="!last">, </span>
            </span>
          </div>
          <div
            *ngIf="post.tags?.nodes && (post.tags?.nodes?.length ?? 0) > 0"
            class="post-tags"
          >
            <span class="taxonomy-label">Tags:</span>
            <span
              *ngFor="let tag of post.tags?.nodes; let last = last"
              class="taxonomy-item"
            >
              {{ tag.name }}<span *ngIf="!last">, </span>
            </span>
          </div>
        </div>

        <a [href]="post.uri || '/posts/' + post.slug" class="read-more">
          Read More
        </a>
      </div>
    </article>
  </div>

  <!-- Empty State -->
  <div
    *ngIf="!loading() && !error() && posts().length === 0"
    class="empty-state"
  >
    <p>No posts found.</p>
  </div>
</div>

// examples/nuxt/data-fetch/example-app/components/templates/Blog.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useGraphQL, gql } from '../../lib/client';
import { getPostsPerPageSync } from '../../lib/utils';
import PostListing from './listing/Post.vue';

// Define pagination props
const props = defineProps({
  page: {
    type: Number,
    default: 1
  },
  category: {
    type: String,
    default: ''
  },
  tag: {
    type: String,
    default: ''
  }
});

// In an async function:
const fetchPosts = async () => {
  const postsPerPage = await getPostsPerPage();
  // Use postsPerPage in your query
};

// Or when you need it synchronously:
const postsPerPage = getPostsPerPageSync();
const isLoading = ref(false);

// Define GraphQL query similar to Next.js implementation
const POSTS_QUERY = gql`
  query GetPosts($first: Int = 9, $after: String, $category: String, $tag: String) {
    posts(
      first: $first, 
      after: $after, 
      where: {
        status: PUBLISH,
        categoryName: $category,
        tag: $tag
      }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`;

// Prepare variables for GraphQL query
const variables = computed(() => {
  return {
    first: postsPerPage,
    after: null,
    category: props.category || null,
    tag: props.tag || null
  };
});

// Fetch initial posts data
const { data, loading, error, refetch } = useGraphQL(
  POSTS_QUERY,
  variables.value
);

// Store all loaded posts
const allPosts = ref([]);
const pageInfo = ref(null);

// Update posts and pageInfo when data changes
const updatePostsData = () => {
  if (data.value?.posts) {
    const edges = data.value.posts.edges || [];

    // For initial load, replace all posts
    if (allPosts.value.length === 0) {
      allPosts.value = edges.map(edge => edge.node);
    }

    // Update pageInfo
    pageInfo.value = data.value.posts.pageInfo;
  }
};

// Watch for data changes to update posts
watch(() => data.value, updatePostsData, { immediate: true });

const loadMorePosts = async () => {
  // Early exit if no more posts or already loading
  if (!pageInfo.value?.hasNextPage || isLoading.value) {
    console.log('Cannot load more: ', {
      hasNextPage: pageInfo.value?.hasNextPage,
      isLoading: isLoading.value
    });
    return;
  }

  isLoading.value = true;
  console.log('Loading more posts with cursor:', pageInfo.value.endCursor);

  try {
    // Explicitly set all variables for clarity
    const loadMoreVariables = {
      first: postsPerPage,
      after: pageInfo.value.endCursor,
      category: props.category || null,
      tag: props.tag || null
    };

    console.log('Load more variables:', loadMoreVariables);

    // Use explicit refetch with all variables
    const result = await refetch(loadMoreVariables);

    console.log('Load more response:', result);

    // Verify the structure of the response
    if (!result.data?.posts?.edges) {
      console.error('Invalid response structure:', result);
      throw new Error('Invalid response structure from GraphQL');
    }

    // Check if we got any new posts
    const newPostsEdges = result.data.posts.edges || [];
    console.log(`Received ${newPostsEdges.length} new posts`);

    if (newPostsEdges.length > 0) {
      // Map to the node structure and add to existing posts
      const newPosts = newPostsEdges.map(edge => edge.node);
      allPosts.value = [...allPosts.value, ...newPosts];

      // Update pageInfo
      pageInfo.value = result.data.posts.pageInfo;
      console.log('Updated pageInfo:', pageInfo.value);
    } else {
      // No new posts were found
      console.log('No new posts found, marking hasNextPage as false');
      pageInfo.value = { ...pageInfo.value, hasNextPage: false };
    }
  } catch (err) {
    console.error('Error loading more posts:', err);
  } finally {
    isLoading.value = false;
  }
};

</script>

<template>
  <div>
    <header>
      <h1>{{ pageTitle }}</h1>
      <p v-if="!props.category && !props.tag">Latest posts and updates</p>
    </header>

    <!-- Error state -->
    <div v-if="error">
      <h2>Error</h2>
      <p>{{ error.message }}</p>
    </div>

    <!-- Initial loading state -->
    <div v-else-if="loading && allPosts.length === 0">
      <p>Loading posts...</p>
    </div>

    <!-- Empty state -->
    <div v-else-if="allPosts.length === 0 && !loading">
      <p>No posts found.</p>
    </div>

    <!-- Post listing -->
    <template v-else>
      <!-- Post listing component -->
      <PostListing :posts="allPosts" :loading="false" :cols="3" />

      <!-- Load more button - similar to BlogList.js -->
      <div v-if="pageInfo?.hasNextPage" class="load-more">
        <button @click="loadMorePosts" type="button" :disabled="isLoading || loading">
          {{ isLoading ? 'Loading...' : 'Load more' }}
        </button>
      </div>
    </template>
  </div>
</template>

<style>
.load-more {
  text-align: center;
  margin-top: 2rem;
}

.load-more button {
  padding: 0.75rem 2rem;
  background-color: #333;
  color: white;
  font-weight: 600;
  border: none;
  border-radius: 0.25rem;
  cursor: pointer;
}

.load-more button:hover {
  background-color: #444;
}

.load-more button:disabled {
  background-color: #999;
  cursor: not-allowed;
}
</style>
