// examples/nuxt/data-fetch/example-app/components/Footer.vue
<script setup>
import { computed } from 'vue';
import { useGraphQL, gql } from '../lib/client';

const FOOTER_QUERY = gql`
  query GetFooterData {
    generalSettings {
      title
    }        
  }
`;

const { 
  data: settingsData, 
  loading: settingsLoading,
} = useGraphQL(FOOTER_QUERY, {}, { 
  key: 'footer-settings',
  loadingText: 'Loading site title...' 
});

const siteInfo = computed(() => {
  const title = settingsData.value?.generalSettings?.title;  
  return {
    title: title
  };
});
const currentYear = new Date().getFullYear();
</script>

 <template>
  <footer v-if="!settingsLoading" class="footer">
      <div class="footer-content">
        <p>© {{ currentYear }} <NuxtLink to="/">{{ siteInfo.title }}</NuxtLink>. All rights reserved.</p>
        <p>Built with WordPress, Nuxt, and WPGraphQL.</p>
      </div>  
  </footer>
</template>

<style scoped lang="scss">
@use '@/assets/scss/components/footer';
</style>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/footer/footer.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GraphQLService, gql } from '../../utils/graphql.service';

interface SiteSettings {
  generalSettings: {
    title: string;
  };
}
@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  siteInfo = signal<{ title: string }>({ title: 'HeadlessWP Toolkit' });
  settingsLoading = signal<boolean>(false);

  currentYear = new Date().getFullYear();
  constructor(private graphqlService: GraphQLService) {}
  ngOnInit() {
    this.loadSiteSettings();
  }
  private loadSiteSettings() {
    if (!this.graphqlService) {
      console.error('GraphQLService is not available');
      return;
    }

    const SETTINGS_QUERY = gql`
      query HeaderSettingsQuery {
        generalSettings {
          title
        }
      }
    `;

    this.settingsLoading.set(true);

    this.graphqlService.query<SiteSettings>(SETTINGS_QUERY, {}).subscribe({
      next: (data: SiteSettings) => {
        if (data?.generalSettings?.title) {
          this.siteInfo.set({ title: data.generalSettings.title });
        }
        this.settingsLoading.set(false);
      },
      error: (error: any) => {
        console.error('Error loading site settings:', error);
        this.settingsLoading.set(false);
      },
    });
  }
}

<footer class="footer">
  <div class="footer-content">
    <p>
      &copy; {{ currentYear }}
      <span *ngIf="siteInfo()?.title && !settingsLoading()">{{
        siteInfo().title
      }}</span
      >. All rights reserved.
    </p>
  </div>
</footer>
