// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/wp-templates/front-page/front-page.component.ts
import { Component, OnInit, signal, Input, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { GraphQLService, gql } from '../../../utils/graphql.service';
import { LoadingComponent } from '../../loading/loading.component';
import { EmptyStateComponent } from '../../empty-state/empty-state.component';
import { PostListingComponent } from '../../post-listing/post-listing.component';

interface GeneralSettings {
  title: string;
  description: string;
}

interface Author {
  node: {
    name: string;
    avatar: {
      url: string;
    };
  };
}

interface Category {
  name: string;
  slug: string;
}

interface FeaturedImage {
  node: {
    sourceUrl: string;
    altText: string;
  };
}

interface Post {
  id: string;
  title: string;
  date: string;
  uri: string;
  slug: string;
  excerpt: string;
  featuredImage?: FeaturedImage;
  author?: Author;
  categories?: {
    nodes: Category[];
  };
}

interface HomeSettingsResponse {
  generalSettings: GeneralSettings;
}

interface HomeBlogPostsResponse {
  posts: {
    nodes: Post[];
  };
}

@Component({
  selector: 'app-front-page',
  standalone: true,
  imports: [
    CommonModule, 
    RouterModule, 
    LoadingComponent, 
    EmptyStateComponent, 
    PostListingComponent
  ],
  templateUrl: './front-page.component.html',
  styleUrl: './front-page.component.scss'
})
export class FrontPageComponent implements OnInit {
  // Signals for reactive state
  settingsLoading = signal(true);
  settingsError = signal<any>(null);
  settingsData = signal<HomeSettingsResponse | null>(null);
  
  blogLoading = signal(true);
  blogError = signal<any>(null);
  blogData = signal<HomeBlogPostsResponse | null>(null);

  // GraphQL Queries
  private HOME_SETTINGS_QUERY = gql`
    query HomeSettingsQuery {
      generalSettings {
        title
        description
      }
    }
  `;

  private HOME_BLOG_POSTS_QUERY = gql`
    query HomeBlogPostsQuery {
      posts(first: 4) {
        nodes {
          id
          title
          date
          uri
          slug
          excerpt
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
        }
      }
    }
  `;

  // Computed properties using Angular signals
  posts = computed(() => {
    return this.blogData()?.posts?.nodes || [];
  });

  siteInfo = computed(() => {
    const settings = this.settingsData()?.generalSettings;
    return {
      title: settings?.title || 'My WordPress Site',
      description: settings?.description || 'Welcome to my site'
    };
  });

  constructor(private graphqlService: GraphQLService) {}

  ngOnInit() {
    this.loadSiteSettings();
    this.loadBlogPosts();
  }

  private loadSiteSettings() {
    console.log('🔍 Loading site settings...');
    
    this.settingsLoading.set(true);
    this.settingsError.set(null);

    this.graphqlService.query<HomeSettingsResponse>(this.HOME_SETTINGS_QUERY, {}).subscribe({
      next: (data) => {
        console.log('✅ Home Settings loaded:', data);
        this.settingsData.set(data);
        this.settingsLoading.set(false);
      },
      error: (error) => {
        console.error('❌ Error loading home settings:', error);
        this.settingsError.set(error);
        this.settingsLoading.set(false);
      }
    });
  }

  private loadBlogPosts() {
    console.log('🔍 Loading recent blog posts...');
    
    this.blogLoading.set(true);
    this.blogError.set(null);

    this.graphqlService.query<HomeBlogPostsResponse>(this.HOME_BLOG_POSTS_QUERY, {}).subscribe({
      next: (data) => {
        console.log('✅ Home Blog Posts loaded:', data);
        this.blogData.set(data);
        this.blogLoading.set(false);
      },
      error: (error) => {
        console.error('❌ Error loading blog posts:', error);
        this.blogError.set(error);
        this.blogLoading.set(false);
      }
    });
  }

  refreshData() {
    this.loadSiteSettings();
    this.loadBlogPosts();
  }
}
<main>
  <section id="hero">
    <!-- Loading state for settings -->
    <ng-container *ngIf="settingsLoading()">
      <app-loading text="Loading site information..."></app-loading>
    </ng-container>

    <!-- Error state for settings -->
    <div *ngIf="settingsError() && !settingsLoading()">
      <h1>My WordPress Site</h1>
      <p>Welcome to my site</p>
      <small>Error loading site data: {{ settingsError()?.message }}</small>
    </div>

    <!-- Success state for settings -->
    <div *ngIf="!settingsLoading() && !settingsError()">
      <h1>{{ siteInfo().title }}</h1>
      <p>{{ siteInfo().description }}</p>
    </div>
  </section>

  <div class="container">
    <section id="recent-posts">
      <h2>Recent Posts</h2>

      <!-- Error state for blog posts -->
      <div *ngIf="blogError() && !blogLoading()">
        <p>Failed to load posts</p>
        <p>{{ blogError()?.message }}</p>
        <button class="btn btn-primary btn-sm" (click)="refreshData()">
          Try Again
        </button>
      </div>

      <!-- Loading state for blog posts -->
      <ng-container *ngIf="blogLoading() && !blogError()">
        <app-loading text="Loading recent posts..."></app-loading>
      </ng-container>

      <!-- Empty state -->
      <ng-container *ngIf="!blogLoading() && !blogError() && posts().length === 0">
        <app-empty-state></app-empty-state>
      </ng-container>

      <!-- Posts listing -->
      <ng-container *ngIf="!blogLoading() && !blogError() && posts().length > 0">
        <app-post-listing 
          [posts]="posts()" 
          [loading]="false" 
          [cols]="4">
        </app-post-listing>
      </ng-container>
    </section>

    <div class="text-center">
      <a routerLink="/blog" class="button button-primary button-large">
        View All Blog Posts →
      </a>
    </div>
  </div>
</main>

// examples/nuxt/template-hierarchy-data-fetching/example-app/components/wp-templates/front-page.vue
<script setup>
import { computed } from "vue";
import { useGraphQL, gql } from "../../lib/client";
import PostListing from "../templates/listing/Post.vue";
import Loading from "../Loading.vue";
import EmptyState from "../EmptyState.vue";

const HOME_SETTINGS_QUERY = gql`
  query HomeSettingsQuery {
    generalSettings {
      title
      description
    }
  }
`;

const HOME_BLOG_POSTS_QUERY = gql`
  query HomeBlogPostsQuery {
    posts(first: 4) {
      nodes {
        id
        title
        date
        uri
        slug
        excerpt
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        author {
          node {
            name
            avatar {
              url
            }
          }
        }
        categories {
          nodes {
            name
            slug
          }
        }
      }
    }
  }
`;

// Use unique keys for proper SSR state management
const {
  data: blogData,
  loading: blogLoading,
  error: blogError,
} = useGraphQL(
  HOME_BLOG_POSTS_QUERY,
  {},
  {
    key: "home-blog-posts-unique",
    loadingText: "Loading recent posts...",
  }
);

const {
  data: settingsData,
  loading: settingsLoading,
  error: settingsError,
} = useGraphQL(
  HOME_SETTINGS_QUERY,
  {},
  {
    key: "home-settings-unique",
    loadingText: "Loading site information...",
  }
);

const posts = computed(() => {
  return blogData.value?.posts?.nodes || [];
});

const siteInfo = computed(() => {
  const title = settingsData.value?.generalSettings?.title;
  const description = settingsData.value?.generalSettings?.description;

  return {
    title: title,
    description: description || "Welcome to my site",
  };
});
</script>

<template>
  <main>
    <section id="hero">
      <template v-if="settingsLoading">
        <Loading text="Loading site information..." />
      </template>

      <template v-else-if="settingsError">
        <div>
          <h1>My WordPress Site1</h1>
          <p>Welcome to my site</p>
          <small>Error loading site data: {{ settingsError.message }}</small>
        </div>
      </template>

      <template v-else>
        <div>
          <h1>{{ siteInfo.title }}</h1>
          <p>{{ siteInfo.description }}</p>
        </div>
      </template>
    </section>

    <div class="container">
      <section id="recent-posts">
        <h2>Recent Posts</h2>

        <template v-if="blogError">
          <div>
            <p>Failed to load posts</p>
            <p>{{ blogError.message }}</p>
          </div>
        </template>

        <template v-else-if="blogLoading">
          <Loading text="Loading recent posts..." />
        </template>

        <template v-else-if="posts.length === 0">
          <EmptyState />
        </template>

        <template v-else>
          <PostListing :posts="posts" :loading="false" :cols="4" />
        </template>
      </section>

      <div class="text-center">
        <NuxtLink to="/blog" class="button button-primary button-large">
          View All Blog Posts →
        </NuxtLink>
      </div>
    </div>
  </main>
</template>

<style scoped lang="scss">
@use "@/assets/scss/pages/home";
</style>
