// examples/nuxt/template-hierarchy-data-fetching/example-app/components/templates/comments/CommentForm.vue
<script setup>
import { ref } from "vue";
import { useMutation, gql } from "../../../lib/client";

const props = defineProps({
  postId: {
    type: Number,
    required: true,
  },
  replyData: {
    type: Object,
    default: null, // 0 means it's a root comment, not a reply
  },
});

const emit = defineEmits(["submit", "cancel", "success", "error"]);

// Form fields
const authorName = ref("");
const authorEmail = ref("");
const commentContent = ref("");
const isSubmitting = ref(false);

// Message states
const errorMessage = ref("");
const successMessage = ref("");
const showMessage = ref(false);

const CREATE_COMMENT = gql`
  mutation CreateComment(
    $commentOn: Int!
    $content: String!
    $author: String!
    $authorEmail: String!
    $parent: ID
  ) {
    createComment(
      input: {
        commentOn: $commentOn
        content: $content
        author: $author
        authorEmail: $authorEmail
        parent: $parent
      }
    ) {
      success
      comment {
        id
        content
        date
        parentId
        author {
          node {
            name
          }
        }
      }
    }
  }
`;

const clearMessages = () => {
  errorMessage.value = "";
  successMessage.value = "";
  showMessage.value = false;
};

const showSuccess = (message) => {
  clearMessages();
  successMessage.value = message;
  showMessage.value = true;

  // Auto-hide success message after 5 seconds
  setTimeout(() => {
    clearMessages();
  }, 5000);
};

const showError = (message) => {
  clearMessages();
  errorMessage.value = message;
  showMessage.value = true;

  setTimeout(() => {
    clearMessages();
  }, 8000);
};

const dismissMessage = () => {
  clearMessages();
};

const submitComment = async () => {
  if (!authorName.value || !authorEmail.value || !commentContent.value) {
    showError("Please fill in all required fields.");
    return;
  }

  isSubmitting.value = true;
  clearMessages();

  try {
    let variables = {
      commentOn: props.postId,
      content: commentContent.value,
      author: authorName.value,
      authorEmail: authorEmail.value,
      parent: null,
    };

    // Add parent ID for replies (only if it's actually a reply)
    if (props.replyData.parentId) {
      // Convert base64 parentId to the needed format and extract the number
      let base64ParentId = atob(`${props.replyData.parentId}`);
      // Extract number from string like "comment:43"
      let parentNumber = parseInt(base64ParentId.split(":")[1], 10);
      variables.parent = parentNumber;
    }

    //console.log("Mutation variables:", variables);

    // Execute the mutation
    const { data, errors } = await useMutation(CREATE_COMMENT, variables);

    if (errors && errors.length > 0) {
      console.error("GraphQL errors:", errors);
      throw new Error(errors[0]?.message || "Failed to submit comment");
    }

    if (!data?.createComment?.success) {
      throw new Error("Comment submission failed");
    }

    //console.log("Comment created:", data.createComment.comment);

    // Show success message
    showSuccess(
      props.replyData
        ? "Your reply has been posted successfully and it is waiting for approval!"
        : "Your comment has been posted successfully and it is waiting for approval!"
    );

    // Emit success event with the new comment
    emit("success", data.createComment.comment);

    // Clear form after successful submission
    authorName.value = "";
    authorEmail.value = "";
    commentContent.value = "";

    // Emit submit event for parent component
    emit("submit", {
      name: authorName.value,
      content: commentContent.value,
      postId: props.postId,
      parent: props.replyData.parentId,
    });
  } catch (error) {
    console.error("Error submitting comment:", error);
    showError(error.message || "Failed to submit comment. Please try again.");
    emit("error", error);
  } finally {
    isSubmitting.value = false;
  }
};

// Cancel reply
const cancelReply = () => {
  // Clear form when canceling
  authorName.value = "";
  authorEmail.value = "";
  commentContent.value = "";
  clearMessages();

  emit("cancel");
};
</script>

<template>
  <div id="comment-form" class="comment-form">
    <h3 class="text-center">
      {{
        replyData ? `Reply to "${replyData.author}" comment` : "Leave a Comment"
      }}
    </h3>
    <!-- Success/Error Message -->
    <div v-if="showMessage" class="message-container">
      <!-- Success Message -->
      <div v-if="successMessage" class="success-message">
        <div class="message-content">
          <span class="message-icon">✓</span>
          <span class="message-text">{{ successMessage }}</span>
        </div>
        <button @click="dismissMessage" class="dismiss-button" type="button">
          ×
        </button>
      </div>

      <!-- Error Message -->
      <div v-if="errorMessage" class="error-message">
        <div class="message-content">
          <span class="message-icon">⚠</span>
          <span class="message-text">{{ errorMessage }}</span>
        </div>
        <button @click="dismissMessage" class="dismiss-button" type="button">
          ×
        </button>
      </div>
    </div>

    <form @submit.prevent="submitComment" class="grid gap-4">
      <div class="grid cols-2 gap-4">
        <div class="flex-1">
          <label for="author-name" class="sr-only"> Name * </label>
          <input
            id="author-name"
            v-model="authorName"
            type="text"
            required
            placeholder="Name*"
          />
        </div>

        <div>
          <label for="author-email" class="sr-only"> Email * </label>
          <input
            id="author-email"
            v-model="authorEmail"
            type="email"
            required
            placeholder="Email* (will not be published)"
          />
        </div>
      </div>

      <div class="row">
        <label for="comment-content" class="sr-only"> Comment * </label>
        <textarea
          id="comment-content"
          v-model="commentContent"
          rows="4"
          required
          placeholder="Your comment*"
        ></textarea>
      </div>

      <div class="">
        <button
          type="submit"
          class="button button-primary"
          :disabled="isSubmitting"
        >
          {{ isSubmitting ? "Posting..." : "Post Comment" }}
        </button>

        <button
          v-if="replyData"
          type="button"
          @click="cancelReply"
          class="button button-secondary"
        >
          Cancel
        </button>
      </div>
    </form>
  </div>
</template>

<style scoped lang="scss">
@use "@/assets/scss/components/comments/comment-form";
</style>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/comments/comment-form/comment-form.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  signal,
  effect,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { gql, executeMutation } from '../../../utils/graphql.service';
import {
  ReplyData,
  CommentFormData,
} from '../../../interfaces/comment.interface';

@Component({
  selector: 'app-comment-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './comment-form.component.html',
  styleUrls: ['./comment-form.component.scss'],
})
export class CommentFormComponent {
  @Input() postId!: number;
  @Input() replyData: ReplyData | null = null;

  @Output() submit = new EventEmitter<CommentFormData>();
  @Output() error = new EventEmitter<Error>();
  @Output() cancel = new EventEmitter<void>();

  isSubmitting = signal<boolean>(false);
  formError = signal<Error | null>(null);
  showSuccess = signal<boolean>(false);

  formData: CommentFormData = {
    author: '',
    email: '',
    url: '',
    content: '',
  };

  private CREATE_COMMENT = gql`
    mutation CreateComment(
      $commentOn: Int!
      $content: String!
      $author: String!
      $authorEmail: String!
      $parent: ID
    ) {
      createComment(
        input: {
          commentOn: $commentOn
          content: $content
          author: $author
          authorEmail: $authorEmail
          parent: $parent
        }
      ) {
        success
        comment {
          id
          content
          date
          parentId
          author {
            node {
              name
            }
          }
        }
      }
    }
  `;

  constructor() {
    effect(() => {
      if (this.showSuccess()) {
        setTimeout(() => {
          this.showSuccess.set(false);
        }, 5000);
      }
    });
  }

  async onSubmit(event: Event): Promise<void> {
    event.preventDefault();

    if (this.isSubmitting()) {
      return;
    }

    if (
      !this.formData.author ||
      !this.formData.email ||
      !this.formData.content
    ) {
      this.formError.set(new Error('Please fill in all required fields.'));
      return;
    }

    try {
      this.isSubmitting.set(true);
      this.formError.set(null);
      this.showSuccess.set(false);

      this.submit.emit({ ...this.formData });

      let variables: any = {
        commentOn: this.postId,
        content: this.formData.content,
        author: this.formData.author,
        authorEmail: this.formData.email,
        parent: null,
      };

      if (this.replyData?.parentId) {
        try {
          const base64ParentId = atob(this.replyData.parentId);
          const parentNumber = parseInt(base64ParentId.split(':')[1], 10);
          variables.parent = parentNumber;
        } catch {
          variables.parent = this.replyData.parentId;
        }
      }

      const result = await executeMutation(this.CREATE_COMMENT, variables);

      if (result.errors && result.errors.length > 0) {
        throw new Error(
          result.errors[0]?.message || 'Failed to submit comment',
        );
      }

      if (!result.data?.createComment?.success) {
        throw new Error('Comment submission failed');
      }

      this.showSuccess.set(true);

      this.resetForm();
    } catch (error: any) {
      const errorMessage = error.message || 'Failed to submit comment';
      const commentError = new Error(errorMessage);

      this.formError.set(commentError);
    } finally {
      this.isSubmitting.set(false);
    }
  }

  onCancel(): void {
    this.cancel.emit();
    this.resetForm();
  }

  clearError(): void {
    this.formError.set(null);
  }

  private resetForm(): void {
    this.formData = {
      author: '',
      email: '',
      url: '',
      content: '',
    };
  }

  get isFormValid(): boolean {
    return !!(
      this.formData.author.trim() &&
      this.formData.email.trim() &&
      this.formData.content.trim() &&
      this.isValidEmail(this.formData.email)
    );
  }

  private isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  /**
   * Simple URL validation (if provided)
   */
  private isValidUrl(url: string): boolean {
    if (!url.trim()) return true; // Empty URL is valid (optional field)

    try {
      new URL(url);
      return true;
    } catch {
      return false;
    }
  }
}

<form
  id="comment-form"
  class="comment-form"
  (ngSubmit)="onSubmit($event)"
  #commentForm="ngForm"
>
  <div *ngIf="replyData" class="reply-to">
    <div>
      Replying to <strong>{{ replyData.author }}</strong>
    </div>
  </div>

  <div *ngIf="isSubmitting()" class="submitting-overlay">
    <p>Submitting your comment...</p>
  </div>

  <div *ngIf="formError()" class="error-message">
    <p>{{ formError()?.message || "Error submitting comment" }}</p>
    <button type="button" (click)="clearError()" class="close-error">×</button>
  </div>

  <div *ngIf="showSuccess()" class="success-message">
    <p>Comment submitted successfully but waiting for approval!</p>
  </div>

  <div class="grid cols-2 gap-4">
    <div class="form-group">
      <label for="author">Name *</label>
      <input
        type="text"
        id="author"
        name="author"
        [(ngModel)]="formData.author"
        required
        maxlength="245"
        placeholder="Your name"
        [disabled]="isSubmitting()"
        #authorField="ngModel"
      />
      <div
        *ngIf="authorField.invalid && commentForm.submitted && !isSubmitting()"
        class="field-error"
      >
        <span *ngIf="authorField.errors?.['required']">Name is required</span>
        <span *ngIf="authorField.errors?.['maxlength']"
          >Name must be less than 245 characters</span
        >
      </div>
    </div>

    <div class="form-group">
      <label for="email">Email *</label>
      <input
        type="email"
        id="email"
        name="email"
        [(ngModel)]="formData.email"
        required
        maxlength="100"
        placeholder="your@email.com"
        [disabled]="isSubmitting()"
        #emailField="ngModel"
      />
      <div
        *ngIf="emailField.invalid && commentForm.submitted && !isSubmitting()"
        class="field-error"
      >
        <span *ngIf="emailField.errors?.['required']">Email is required</span>
        <span *ngIf="emailField.errors?.['email']"
          >Please enter a valid email</span
        >
        <span *ngIf="emailField.errors?.['maxlength']"
          >Email must be less than 100 characters</span
        >
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="url">Website</label>
    <input
      type="url"
      id="url"
      name="url"
      [(ngModel)]="formData.url"
      maxlength="200"
      placeholder="https://yourwebsite.com"
      [disabled]="isSubmitting()"
      #urlField="ngModel"
    />
    <div
      *ngIf="urlField.invalid && commentForm.submitted && !isSubmitting()"
      class="field-error"
    >
      <span *ngIf="urlField.errors?.['url']">Please enter a valid URL</span>
      <span *ngIf="urlField.errors?.['maxlength']"
        >URL must be less than 200 characters</span
      >
    </div>
  </div>

  <div class="form-group">
    <label for="content">Comment *</label>
    <textarea
      id="content"
      name="content"
      [(ngModel)]="formData.content"
      required
      rows="2"
      placeholder="Write your comment here..."
      [disabled]="isSubmitting()"
      #contentField="ngModel"
    ></textarea>
    <div
      *ngIf="contentField.invalid && commentForm.submitted && !isSubmitting()"
      class="field-error"
    >
      <span *ngIf="contentField.errors?.['required']"
        >Comment content is required</span
      >
    </div>
  </div>
  <div class="form-actions text-center">
    <button
      type="submit"
      [disabled]="commentForm.invalid || isSubmitting()"
      class="button button-primary submit-comment"
    >
      {{
        isSubmitting()
          ? "Submitting..."
          : replyData
            ? "Post Reply"
            : "Post Comment"
      }}
    </button>

    <button
      *ngIf="replyData"
      type="button"
      (click)="onCancel()"
      class="button button-secondary cancel-comment"
      [disabled]="isSubmitting()"
    >
      Cancel Reply
    </button>
  </div>
</form>
