// examples/nuxt/template-hierarchy-data-fetching/example-app/components/wp-templates/home.vue
<script setup>
import { computed, ref } from "vue";
import { gql } from "../../lib/client";
import { capitalizeWords, getPosts } from "../../lib/utils";
import PostListing from "../templates/listing/Post.vue";
import LoadMore from "../blog/LoadMore.vue";
import EmptyState from "../EmptyState.vue";
import Loading from "../Loading.vue";

const props = defineProps({
  category: {
    type: String,
    default: "",
  },
  tag: {
    type: String,
    default: "",
  },
  titlePrefix: {
    type: String,
    default: "Blog",
  },
});

// Get the slug based on category or tag
const slug = props.category || props.tag || "";

// Format title
const pageTitle = computed(() => {
  const capitalizedSlug = capitalizeWords(slug);

  if (capitalizedSlug) {
    return `${props.titlePrefix}: ${capitalizedSlug}`;
  }

  return props.titlePrefix;
});

const POSTS_QUERY = gql`
  query GetPosts(
    $first: Int = 9
    $after: String
    $category: String
    $tag: String
  ) {
    posts(
      first: $first
      after: $after
      where: { categoryName: $category, tag: $tag }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          tags {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`;

const postsPerPage = 5; // Fetch 5 posts initially
// Track loading state
const loading = ref(true);
const error = ref(null);

// Fetch initial posts
let data;

try {
  data = await getPosts({
    query: POSTS_QUERY,
    slug,
    pageSize: postsPerPage,
    revalidate: 3600, // Caches for 60 minutes
  });
  loading.value = false;
} catch (err) {
  error.value = err;
  loading.value = false;
  data = null;
}

// Extract initial posts and pageInfo
const allPosts = ref(data?.posts?.edges?.map((edge) => edge.node) || []);
const initialPageInfo = data?.posts?.pageInfo || {};

// Handle new posts from client component
const handleNewPosts = (newPosts) => {
  allPosts.value = [...allPosts.value, ...newPosts];
};

// Handle loading state
const handleLoading = (isLoading) => {
  loading.value = isLoading;
};
</script>

<template>
  <div class="container mx-auto p-4 max-w-3xl">
    <header>
      <h1>{{ pageTitle }}</h1>
    </header>

    <!-- Error state -->
    <div v-if="error">
      <h2>Error</h2>
      <p>{{ error.message || "An error occurred while loading posts" }}</p>
    </div>

    <!-- Loading state -->
    <div v-else-if="loading && allPosts.length === 0">
      <Loading />
    </div>

    <!-- Empty state -->
    <div v-else-if="allPosts.length === 0">
      <EmptyState text="No posts found" />
    </div>

    <!-- Initial SSR and client-side component for pagination -->
    <template v-else>
      <!-- All posts rendered in a single component -->
      <PostListing :posts="allPosts" :loading="loading" :cols="3" />

      <!-- Client component for pagination (only button) -->
      <LoadMore
        :initial-posts="allPosts"
        :initial-page-info="initialPageInfo"
        :posts-per-page="postsPerPage"
        :posts-query="POSTS_QUERY"
        :category="props.category"
        :tag="props.tag"
        @update:posts="handleNewPosts"
        @loading="handleLoading"
      />
    </template>
  </div>
</template>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/wp-templates/home/home.component.ts
import { Component, OnInit, Input, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { getPosts, capitalizeWords } from '../../../utils/utils';
import { LoadingComponent } from '../../loading/loading.component';
import { EmptyStateComponent } from '../../empty-state/empty-state.component';
import { PostListingComponent } from '../../post-listing/post-listing.component';
import {
  Post,
  PageInfo,
  PostsResponse,
} from '../../../interfaces/post.interface';

const POSTS_QUERY = `
  query GetPosts(
    $first: Int = 9
    $after: String
    $category: String
    $tag: String
  ) {
    posts(
      first: $first
      after: $after
      where: { categoryName: $category, tag: $tag }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          tags {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`;

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    LoadingComponent,
    EmptyStateComponent,
    PostListingComponent,
  ],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent implements OnInit {

  @Input() category: string = '';
  @Input() tag: string = '';
  @Input() titlePrefix: string = 'Blog';

  allPosts = signal<Post[]>([]);
  initialPageInfo = signal<PageInfo | null>(null);
  loading = signal<boolean>(true);
  error = signal<string | null>(null);
  loadingMore = signal<boolean>(false);

  postsPerPage: number = 9;
  private currentSlug: string = '';

  // Computed property for page title
  pageTitle = computed(() => {
    const capitalizedSlug = capitalizeWords(this.currentSlug);
    if (capitalizedSlug) {
      return `${this.titlePrefix}: ${capitalizedSlug}`;
    }
    return this.titlePrefix;
  });

  constructor() {}

  async ngOnInit(): Promise<void> {
    await this.loadPosts();
  }
  /**
   * Load posts using the getPosts utility function
   */
  private async loadPosts(after: string | null = null): Promise<void> {
    try {
      if (!after) {
        this.loading.set(true);
        this.error.set(null);
      } else {
        this.loadingMore.set(true);
      }

      // Use getPosts utility function
      const data = await getPosts({
        query: POSTS_QUERY,
        slug: '',
        pageSize: this.postsPerPage,
        after,
      });

      if (data?.posts) {
        this.processPosts(data);
      } else {
        this.error.set('No posts data received');
      }
    } catch (error: any) {
      this.error.set(error.message || 'Failed to load posts');
    } finally {
      this.loading.set(false);
      this.loadingMore.set(false);
    }
  }

  private processPosts(data: PostsResponse): void {
    if (data.posts?.edges) {
      const newPosts = data.posts.edges.map((edge) => edge.node);

      // If it's the first load, replace all posts
      // If it's load more, append to existing posts
      if (this.allPosts().length === 0) {
        this.allPosts.set(newPosts);
      } else {
        this.allPosts.update((currentPosts) => [...currentPosts, ...newPosts]);
      }

      this.initialPageInfo.set(data.posts.pageInfo);
    }
  }

  async loadMorePosts(): Promise<void> {
    const pageInfo = this.initialPageInfo();
    if (pageInfo?.hasNextPage && pageInfo.endCursor && !this.loadingMore()) {
      await this.loadPosts(pageInfo.endCursor);
    }
  }

  async refreshPosts(): Promise<void> {
    this.allPosts.set([]);
    this.initialPageInfo.set(null);
    await this.loadPosts();
  }

  hasMorePosts(): boolean {
    const pageInfo = this.initialPageInfo();
    return pageInfo?.hasNextPage || false;
  }

  getPostsCount(): number {
    return this.allPosts().length;
  }

  /**
   * Handles new posts emitted from the LoadMoreComponent.
   * Appends new posts to the existing list.
   * @param newPosts - Array of new Post objects
   */
  handleNewPosts(newPosts: Post[]): void {
    this.allPosts.update((currentPosts) => [...currentPosts, ...newPosts]);
  }

  handleLoading(isLoading: boolean): void {
    this.loadingMore.set(isLoading);
  }
}

<div class="container">
  <header class="page-header text-center mt-4">
    <h1>{{ pageTitle() }}</h1>
  </header>

  <section *ngIf="loading() && allPosts().length === 0">
    <app-loading text="Loading posts..."></app-loading>
  </section>

  <section *ngIf="error() && !loading()">
    <div class="error-container">
      <h2>Error Loading Posts</h2>
      <p>{{ error() }}</p>
      <button (click)="refreshPosts()" class="button button-primary">
        Try Again
      </button>
    </div>
  </section>

  <section *ngIf="!loading() && !error() && allPosts().length > 0">
    <app-post-listing [posts]="allPosts()" [loading]="false" [cols]="3">
    </app-post-listing>

    <div class="load-more-section text-center" *ngIf="hasMorePosts()">
      <div *ngIf="loadingMore()" class="loading-more">
        <app-loading text="Loading more posts..."></app-loading>
      </div>

      <button
        *ngIf="!loadingMore()"
        (click)="loadMorePosts()"
        class="button button-primary button-large"
      >
        Load More
        <span class="posts-count">({{ getPostsCount() }} loaded)</span>
      </button>
    </div>
  </section>

  <section *ngIf="!loading() && !error() && allPosts().length === 0">
    <app-empty-state [text]="'No posts found.'"> </app-empty-state>
  </section>
</div>
