// examples/angular/example-app/src/app/components/blog/blog.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GraphQLService, GraphQLStateService, gql } from '../../shared/utils/graphql.service';

interface Post {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  slug: string;
  uri: string;
  featuredImage?: {
    node: {
      sourceUrl: string;
      altText: string;
    };
  };
  categories?: {
    nodes: Array<{
      name: string;
      slug: string;
    }>;
  };
  tags?: {
    nodes: Array<{
      name: string;
      slug: string;
    }>;
  };
  author?: {
    node: {
      name: string;
      avatar: {
        url: string;
      };
    };
  };
}

interface PostsResponse {
  posts: {
    pageInfo: {
      hasNextPage: boolean;
      endCursor: string;
    };
    edges: Array<{
      cursor: string;
      node: Post;
    }>;
  };
}

@Component({
  selector: 'app-blog',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './blog.component.html',
  styleUrl: './blog.component.css'
})
export class BlogComponent implements OnInit {
  // Reactive signals
  postsData = signal<PostsResponse | null>(null);
  loading = signal<boolean>(false);
  error = signal<string | null>(null);

  // Computed signal to extract posts from the response
  posts = signal<Post[]>([]);

  private postsQuery: any;

  constructor(
    private graphqlService: GraphQLService,
    private graphqlState: GraphQLStateService
  ) {}

  ngOnInit() {
    // Create and execute the query
    this.postsQuery = this.graphqlState.createQuery<PostsResponse>(
      gql`
  query GetPosts(
    $first: Int = 9
    $after: String
    $category: String
    $tag: String
  ) {
    posts(
      first: $first
      after: $after
      where: { categoryName: $category, tag: $tag }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          tags {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`, {first: 10});

    // Subscribe to reactive state
    this.postsData = this.postsQuery.data;
    this.loading = this.postsQuery.loading;
    this.error = this.postsQuery.error;

    // Extract posts from the GraphQL response structure
    this.setupPostsExtraction();
  }

  private setupPostsExtraction() {
    // Use effect to update posts when data changes
    // For now, we'll do this manually in a simple way
    // You could use Angular's effect() here for more reactive approach
    const updatePosts = () => {
      const data = this.postsData();
      if (data?.posts?.edges) {
        const extractedPosts = data.posts.edges.map(edge => edge.node);
        this.posts.set(extractedPosts);
      } else {
        this.posts.set([]);
      }
    };

    // Update posts when data changes
    // For now, we'll call this periodically or on data updates
    updatePosts();
  }

  loadMorePosts() {
    // Example of refetching with new variables
    this.postsQuery.setVariables({ first: 20 }).subscribe({
      next: (result: any) => console.log('Loaded more posts:', result),
      error: (err: any) => console.error('Error loading more posts:', err)
    });
  }

  refreshPosts() {
    // Example of refetching with same variables
    this.postsQuery.refetch().subscribe({
      next: (result: any) => console.log('Refreshed posts:', result),
      error: (err: any) => console.error('Error refreshing posts:', err)
    });
  }
}

// examples/nuxt/data-fetch/example-app/components/wp-templates/blog.vue
<script setup>
import { computed, ref } from 'vue';
import { gql } from '../../lib/client';
import { capitalizeWords, getPosts } from '../../lib/utils';
import PostListing from '../templates/listing/Post.vue';
import LoadMore from '../blog/LoadMore.vue';

const props = defineProps({
  category: {
    type: String,
    default: ''
  },
  tag: {
    type: String,
    default: ''
  },
  titlePrefix: {
    type: String,
    default: 'Blog'
  }
});

// Get the slug based on category or tag
const slug = props.category || props.tag || '';

// Format title
const pageTitle = computed(() => {
  const capitalizedSlug = capitalizeWords(slug);

  if (capitalizedSlug) {
    return `${props.titlePrefix}: ${capitalizedSlug}`;
  }

  return props.titlePrefix;
});

const POSTS_QUERY = gql`
  query GetPosts($first: Int = 9, $after: String, $category: String, $tag: String) {
    posts(
      first: $first, 
      after: $after, 
      where: {
        categoryName: $category,
        tag: $tag
      }
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          date
          excerpt
          uri
          slug
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
          categories {
            nodes {
              name
              slug
            }
          }
          tags {
            nodes {
              name
              slug
            }
          }
          author {
            node {
              name
              avatar {
                url
              }
            }
          }
        }
      }
    }
  }
`;

const postsPerPage = 6; // Fetch 5 posts initially
// Track loading state
const loading = ref(true);
const error = ref(null);

// Fetch initial posts
let data;

try {
  data = await getPosts({
    query: POSTS_QUERY,
    slug,
    pageSize: postsPerPage,
    revalidate: 3600, // Caches for 60 minutes
  });
  loading.value = false;
} catch (err) {
  error.value = err;
  loading.value = false;
  data = null;
}

// Extract initial posts and pageInfo
const allPosts = ref(data?.posts?.edges?.map(edge => edge.node) || []);
const initialPageInfo = data?.posts?.pageInfo || {};

// Handle new posts from client component
const handleNewPosts = (newPosts) => {
  allPosts.value = [...allPosts.value, ...newPosts];
};

// Handle loading state
const handleLoading = (isLoading) => {
  loading.value = isLoading;
};
</script>

<template>
  <div class="container mx-auto p-4 max-w-3xl">
    <header>
      <h1>{{ pageTitle }}</h1>
    </header>

    <!-- Error state -->
    <div v-if="error">
      <h2>Error</h2>
      <p>{{ error.message || 'An error occurred while loading posts' }}</p>
    </div>

    <!-- Loading state -->
    <div v-else-if="loading && allPosts.length === 0">
      <p>Loading posts...</p>
    </div>

    <!-- Empty state -->
    <div v-else-if="allPosts.length === 0">
      <p>No posts found.</p>
    </div>

    <!-- Initial SSR and client-side component for pagination -->
    <template v-else>
      <!-- All posts rendered in a single component -->
      <PostListing :posts="allPosts" :loading="loading" :cols="3" />

      <!-- Client component for pagination (only button) -->
      <LoadMore :initial-posts="allPosts" :initial-page-info="initialPageInfo" :posts-per-page="postsPerPage"
        :posts-query="POSTS_QUERY" :category="props.category" :tag="props.tag" @update:posts="handleNewPosts"
        @loading="handleLoading" />
    </template>
  </div>
</template>
