// examples/nuxt/template-hierarchy-data-fetching/example-app/components/templates/comments/CommentItem.vue
<script setup>
import { computed } from "vue";
import { formatDate } from "~/lib/utils";
const props = defineProps({
  comment: {
    type: Object,
    required: true,
  },
});

defineEmits(["reply"]);

const avatarUrl = computed(() => {
  return (
    props.comment.author?.node?.avatar?.url ||
    `https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y`
  );
});

const authorName = computed(() => {
  return props.comment.author?.node?.name || "Anonymous";
});

const authorUrl = computed(() => {
  return props.comment.author?.node?.url;
});
</script>

<template>
  <article class="comment-item">
    <div class="comment-meta">
      <img
        :src="avatarUrl"
        :alt="`${authorName}'s avatar`"
        class="comment-avatar"
      />
      <div class="comment-info">
        <div class="comment-author">
          <a
            v-if="authorUrl"
            :href="authorUrl"
            target="_blank"
            rel="noopener noreferrer"
            class="author-link"
          >
            {{ authorName }}
          </a>
          <span v-else class="author-name">{{ authorName }}</span>
        </div>
        <time class="comment-date" :datetime="comment.date">
          {{ formatDate(comment.date) }}
        </time>
      </div>
    </div>

    <div class="comment-content" v-html="comment.content"></div>

    <div class="comment-actions">
      <button
        @click="$emit('reply', comment)"
        class="button button-secondary button-small reply-button"
      >
        Reply
      </button>
    </div>
  </article>
</template>

<style scoped>
@import "/assets/scss/components/comments/comment-item.scss";
</style>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/comments/comment-item/comment-item.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  computed,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Comment } from '../../../interfaces/comment.interface';
import { formatDate } from '../../../utils/utils';

@Component({
  selector: 'app-comment-item',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './comment-item.component.html',
  styleUrl: './comment-item.component.scss',
})
export class CommentItemComponent {
  @Input() comment!: Comment;
  @Output() reply = new EventEmitter<Comment>();

  avatarUrl = computed(() => {
    return (
      this.comment?.author?.node?.avatar?.url ||
      `https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mp&f=y`
    );
  });

  authorName = computed(() => {
    return this.comment?.author?.node?.name || 'Anonymous';
  });

  authorUrl = computed(() => {
    return this.comment?.author?.node?.url;
  });

  formatDate(dateString: string): string {
    return formatDate(dateString);
  }

  onReply(): void {
    this.reply.emit(this.comment);
  }
}

<article class="comment-item">
  <div class="comment-meta">
    <img
      [src]="avatarUrl()"
      [alt]="authorName() + '\'s avatar'"
      class="comment-avatar"
      loading="lazy"
    />
    <div class="comment-info">
      <div class="comment-author">
        <a
          *ngIf="authorUrl(); else authorNameTemplate"
          [href]="authorUrl()"
          target="_blank"
          rel="noopener noreferrer"
          class="author-link"
        >
          {{ authorName() }}
        </a>
        <ng-template #authorNameTemplate>
          <span class="author-name">{{ authorName() }}</span>
        </ng-template>
      </div>
      <time class="comment-date" [attr.datetime]="comment.date">
        {{ formatDate(comment.date) }}
      </time>
    </div>
  </div>

  <div class="comment-content" [innerHTML]="comment.content"></div>

  <div class="comment-actions">
    <button
      (click)="onReply()"
      class="button button-secondary button-small reply-button"
      type="button"
    >
      Reply
    </button>
  </div>
</article>
