// examples/nuxt/template-hierarchy-data-fetching/example-app/components/EmptyState.vue
<script setup>
import { defineProps } from "vue";

const props = defineProps({
  text: {
    type: String,
    default: "", // Default to empty string, so text only shows if provided
  },
});
</script>

<template>
  <div class="empty-state-container text-center">
    <p v-if="text" class="loading-text">{{ text }}</p>
    <p v-else class="loading-text">Nothing to see here yet.</p>
  </div>
</template>

// examples/angular/template-hierarchy-data-fetching/example-app/src/app/components/empty-state/empty-state.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-empty-state',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './empty-state.component.html',
  styleUrl: './empty-state.component.scss',
})
export class EmptyStateComponent {
  @Input() text: string = ''; // Default to empty string, so text only shows if provided
}

<div class="empty-state-container text-center">
  <p *ngIf="text; else defaultText" class="loading-text">{{ text }}</p>
  <ng-template #defaultText>
    <p class="loading-text">Nothing to see here yet.</p>
  </ng-template>
</div>
